package hu.kek.Adatok;

import java.util.ArrayList;

/**
 * Created by Bence on 2017. 01. 22..
 */

public class AdatSzamozatlan {

    public static final String getSzamozatlan(int szamozatlanSzama) {
        if(szamozatlan[szamozatlanSzama-1] != null) {
            return szamozatlan[szamozatlanSzama-1];
        }
        return "";
    }

    public static final String getSzamozatlanTiszta(int szamozatlanSzama) {
        if(szamozatlanTiszta[szamozatlanSzama-1] != null) {
            return szamozatlanTiszta[szamozatlanSzama-1][1];
        }
        return "";
    }

    public static ArrayList kereses (String eredeti) {
        eredeti = eredeti.toLowerCase();
        String keresendo = "(.*)"+eredeti+"(.*)";
        ArrayList<String[]> vissza = new ArrayList<>();
        for (int i = 0; i < szamozatlanTiszta.length; ++i) {
            String aktSzoveg = szamozatlanTiszta[i][1];
            aktSzoveg = aktSzoveg.toLowerCase();
            if(aktSzoveg.matches(keresendo)) {
                String szovegben = szamozatlanTiszta[i][1].substring(aktSzoveg.split(eredeti)[0].length(), aktSzoveg.split(eredeti)[0].length()+eredeti.length());
                vissza.add(new String[] {szamozatlanTiszta[i][0], szamozatlanTiszta[i][1].replaceAll(szovegben, "_<span class=\"kiemel\">$0</span>_")});
            }
        }
        return vissza;
    }

    public static ArrayList szavasKereses (String eredeti) {
        eredeti = eredeti.toLowerCase();
        String keresendo = "(.*)[('„»\\-\\s]"+eredeti+"[\\s\\-«”').,!?:;](.*)";
        ArrayList<String[]> vissza = new ArrayList<>();
        for (int i = 0; i < szamozatlanTiszta.length; ++i) {
            String aktSzoveg = szamozatlanTiszta[i][1];
            aktSzoveg = aktSzoveg.toLowerCase();
            if(aktSzoveg.matches(keresendo)) {
                String szovegben = szamozatlanTiszta[i][1].substring(aktSzoveg.split(eredeti)[0].length(), aktSzoveg.split(eredeti)[0].length()+eredeti.length());
                vissza.add(new String[] {szamozatlanTiszta[i][0], szamozatlanTiszta[i][1].replaceAll("[('„»\\-\\s]"+szovegben+"[\\s\\-«”').,!?:;]", "_<span class=\"kiemel\">$0</span>_")});
            }
        }
        return vissza;
    }

    private static ArrayList keres (String keresendo, String eredeti) {
        ArrayList<String[]> vissza = new ArrayList<>();
        for (int i = 0; i < szamozatlanTiszta.length; ++i) {
            String aktSzoveg = szamozatlanTiszta[i][1];
            aktSzoveg = aktSzoveg.toLowerCase();
            if(aktSzoveg.matches(keresendo)) {
                String szovegben = szamozatlanTiszta[i][1].substring(aktSzoveg.split(eredeti)[0].length(), aktSzoveg.split(eredeti)[0].length()+eredeti.length());
                vissza.add(new String[] {szamozatlanTiszta[i][0], szamozatlanTiszta[i][1].replaceAll(szovegben, "_<span class=\"kiemel\">"+szovegben+"</span>_")});
            }
        }
        return vissza;
    }

    private static final String szamozatlan[] = {
            "<span class=\"szidezet\">„Atyám, ... az örök élet az, hogy megismerjenek téged, az egyedül igaz Istent, és akit küldtél, Jézus Krisztust” (Jn 17,3). „Isten, a mi Üdvözítőnk ... azt akarja, hogy minden ember üdvözüljön és eljusson az igazság ismeretére” (1Tim 2,3–4). „Nem adatott más név az ég alatt az embereknek, amelyben üdvözülhetnének” (ApCsel 4,12), csak Jézus Neve. </span>",
            "<span class=\"szkulonallo\"><table border=\"1\"><tr><td><b>Apostoli hitvallás</b><a href=\"#lj215\" name=\"ljl215\"><span class=\"labjegylink\">[215]</span></a></td><td><b>Nicea–konstantinápolyi hitvallás</b><a href=\"#lj216\" name=\"ljl216\"><span class=\"labjegylink\">[216]</span></a>  </td></tr><tr><td>Hiszek egy Istenben, mindenható Atyában, mennynek és földnek Teremtőjében.</td><td>Hiszek az egy Istenben, mindenható Atyában, mennynek és földnek, minden láthatónak és láthatatlannak Teremtőjében.</td></tr><tr><td>És Jézus Krisztusban, az ő egyszülött Fiában, a mi Urunkban;</td><td>Hiszek az egy Úrban, Jézus Krisztusban, Isten egyszülött Fiában, aki az Atyától született az idők kezdete előtt. Isten az Istentől, Világosság a Világosságtól, valóságos Isten a valóságos Istentől, született, de nem teremtmény, az Atyával egylényegű, és minden általa lett. Értünk, emberekért, a mi üdvösségünkért leszállott a mennyből.</td></tr><tr><td rowspan=\"2\">aki fogantatott Szentlélektől, született Szűz Máriától; szenvedett Poncius Pilátus alatt; megfeszítették, meghalt és eltemették. Alászállt a poklokra, harmadnapon feltámadt a halottak közül; fölment a mennybe, ott ül a mindenható Atyaisten jobbján; onnan jön el ítélni élőket és holtakat.</td><td>Megtestesült a Szentlélek erejéből Szűz Máriától, és emberré lett. Poncius Pilátus alatt értünk keresztre feszítették, kínhalált szenvedett és eltemették.</td></tr><tr><td>Harmadnapra föltámadott a halottak közül; az Írások szerint, fölment a mennybe, ott ül az Atyának jobbján, de újra eljön dicsőségben ítélni élőket és holtakat, és országának nem lesz vége.</td></tr><tr><td>Hiszek Szentlélekben.</td><td>Hiszek a Szentlélekben Urunkban és éltetőnkben, aki az Atyától és a Fiútól származik; akit éppúgy imádunk és dicsőítünk, mint az Atyát és a Fiút. Ő szólt a próféták szavával.</td></tr><tr><td>Hiszem a katolikus Anyaszentegyházat, a szentek közösségét, a bűnök bocsánatát, a test föltámadását és az örök életet. Amen.</td><td>Hiszek az egy, szent, katolikus és apostoli Anyaszentegyházban, vallom az egy keresztséget a bűnök bocsánatára, várom a holtak feltámadását és az eljövendő örök életet. Amen.</td></tr></table></span>",
            "<span class=\"szidezet\">Akkor Mózes mondta Istennek: „Íme, én elmegyek Izrael fiaihoz, és mondom nekik: »Atyáitok Istene küldött engem hozzátok«. Ha mondják majd nekem: »Mi az ő neve?«, mit mondjak nekik?” Akkor Isten válaszolta Mózesnek: „Én vagyok aki vagyok.” Mondta: „Így mondd Izrael fiainak: »Aki vagyok« küldött engem hozzátok. (...) Ez az én nevem mindörökre, és ez az én emlékezetem nemzedékről nemzedékre.” (Kiv 3,13–15)</span>",
            "<span class=\"szkulonallo\">„A búcsú Isten színe előtt a már megbocsátott bűnökért járó, ideigtartó büntetések elengedése, melyet a keresztény hívő, aki megfelelően fölkészült és teljesítette a kiszabott föltételeket, elnyer az Egyház segítségével, amely mint a megváltás szolgálója Krisztus és a szentek elégtételt nyújtó érdemeinek kincstárát hivatalosan kezeli és abban részesít.” <a href=\"#lj2343\" name=\"ljl2343\"><span class=\"labjegylink\">[2343]</span></a> <br /><span class=\"behuzas\">„A</span> búcsú részleges vagy teljes, attól függően, hogy a bűnökért járó ideigtartó büntetéstől részlegesen vagy teljesen szabadít-e meg.” <a href=\"#lj2344\" name=\"ljl2344\"><span class=\"labjegylink\">[2344]</span></a>  „Minden hívő nyerhet búcsúkat (...) önmaga számára vagy az elhunytak javára.” <a href=\"#lj2345\" name=\"ljl2345\"><span class=\"labjegylink\">[2345]</span></a></span>",
            "<span class=\"szkulonallo\">Az emberi cselekedetek erkölcsisége függ:<br /> – a választott tárgytól;<br /> – a kitűzött céltól vagyis a szándéktól;<br /> – a cselekedet körülményeitől.</span>",
            "<span class=\"szidezet\">„A szentek közössége téged dicsőít, <br />és amikor megkoronázod érdemeiket, <br />a Te ajándékaidat koronázod meg.” <a href=\"#lj2853\" name=\"ljl2853\"><span class=\"labjegylink\">[2853]</span></a>  </span>",
            "<span class=\"szkulonallo\"><table border=\"1\"><tr><td><b>Kivonulás 20,2–17.</b></td><td><b>Második Törvénykönyv 5,6–21.</b></td><td><b>Kateketikai formula</b><a href=\"#lj2885\" name=\"ljl2885\"><span class=\"labjegylink\">[2885]</span></a></td></tr><tr><td>\"Én vagyok az Úr, a te Istened, aki kivezettelek téged Egyiptom földjéről, a szolgaság házából. Ne legyenek idegen isteneid előttem. Ne csinálj magadnak faragott képet, vagy hasonmást arról, ami fent van az égben, vagy lenn a földön, vagy a vizekben, a föld alatt. Ne borulj le  ilyen képek előtt és ne tiszteld őket, mert Én az Úr, a te Istened, féltékeny Isten vagyok. Azoknak vétkét, akik gyűlölnek engem, megtorlom fiaikon, unokáikon és dédunokáikon, de ezredízig irgalmasságot gyakorlok azokkal, akik szeretnek, és megtartják parancsaimat.</td><td>\"Én vagyok az Úr, a te Istened, aki kivezettelek téged Egyiptom földjéről, a szolgaság házából. Ne legyenek idegen isteneid a színem előtt.</td><td>\"Én vagyok az Úr, a te Istened: Ne legyenek más isteneid előttem.</td></tr><tr><td>Uradnak, Istenednek nevét ne vedd hiába, mert az Úr nem hagyja büntetlenül azt, aki a nevét hiába veszi.</td><td>Uradnak, Istenednek nevét ne vedd hiába...</td><td>Ne vedd hiába a te Uradnak, Istenednek nevét.</td></tr><tr><td>Gondolj a szombatra és szenteld meg. Hat napig dolgozzál és végezd minden munkádat; a hetedik nap azonban az Úrnak, a te Istenednek szombatja; semmiféle munkát nem szabad végezned sem neked, sem fiadnak, sem lányodnak, sem szolgádnak, sem szolgálódnak, sem állatodnak, sem az idegennek, aki kapuidon belül tartózkodik. Az Úr ugyanis hat nap alatt teremtette az eget és a földet, a tengert és mindent, ami bennük van, a hetedik nap azonban megpihent. Ezért az Úr a szombatot megáldotta és megszentelte.</td><td>Tartsd meg a szombatot, hogy megszenteld.</td><td>Megemlékezzél arról, hogy az ünnepnapokat megszenteld.</td></tr><tr><td>Tiszteld atyádat és anyádat, hogy sokáig élj azon a földön, amelyet az Úr, a te Istened ad neked.</td><td>Tiszteld atyádat és anyádat.</td><td>Tiszteld atyádat és anyádat.</td></tr><tr><td>Ne ölj.</td><td>Ne ölj.</td><td>Ne ölj.</td></tr><tr><td>Ne paráználkodjál.</td><td>Ne paráználkodjál.</td><td>Ne paráználkodjál.</td></tr><tr><td>Ne lopj.</td><td>Ne lopj.</td><td>Ne lopj.</td></tr><tr><td>Ne szólj hamis tanúságot felebarátod ellen.</td><td>Ne szólj hamis tanúságot felebarátod ellen.</td><td>Ne szólj hamis tanúságot felebarátod ellen.</td></tr><tr><td>Ne kívánd felebarátod házát:</td><td>Ne kívánd felebarátod feleségét.</td><td>Ne kívánd feleségét.</td></tr><tr><td>Ne kívánd feleségét, szolgáját, szolgálóját, ökrét, szamarát, sem más egyebet, ami az övé.\"</td><td>Ne kívánd (...) semmijét, ami az övé.\"</td><td>Ne kívánd a javait.\"</td></tr></table></span>",
            "<span class=\"szidezet\">„Én vagyok az Úr, a te Istened, aki kivezettelek téged Egyiptom földjéről, a szolgaság házából. Ne legyenek idegen isteneid előttem. Ne csinálj magadnak faragott képet, vagy hasonmást arról, ami fent van az égben, vagy lenn a földön, vagy a vizekben, a föld alatt. Ne borulj le ilyen képek előtt és ne tiszteld őket.” (Kiv 20,2–5) <a href=\"#lj2909\" name=\"ljl2909\"><span class=\"labjegylink\">[2909]</span></a> <br /><span class=\"behuzas\">„Írva</span>  van ugyanis: Uradat, Istenedet imádd, és csak neki szolgálj!” (Mt 4,10)</span>",
            "<span class=\"szidezet\">„Ne vedd hiába a te Uradnak, Istenednek Nevét” (Kiv 20,7). <a href=\"#lj2974\" name=\"ljl2974\"><span class=\"labjegylink\">[2974]</span></a> <br /><span class=\"behuzas\">„Mondatott</span> a régieknek: »Ne esküdjél hamisan« (...) Én pedig azt mondom nektek: Egyáltalán ne esküdjetek.” (Mt 5,33–34) </span>",
            "<span class=\"szidezet\">„Gondolj a szombatra, és szenteld meg. Hat napig dolgozzál és végezd minden munkádat. A hetedik nap azonban az Úmak, a te Istenednek szombatja, ezért semmiféle munkát nem szabad végezned.” (Kiv 20,8– 10) <a href=\"#lj2989\" name=\"ljl2989\"><span class=\"labjegylink\">[2989]</span></a> <br /><span class=\"behuzas\">„A</span> szombat van az emberért, nem az ember a szombatért. Az Emberfia ura a szombatnak is.” (Mk 2,27–28) </span>",
            "<span class=\"szidezet\">„Ezt a napot az Úr Isten adta, ujjongjunk és vigadjunk rajta!” (Zsolt 118,24) </span>",
            "<span class=\"szidezet\">Jézus így szólt tanítványaihoz: „Amint én szerettelek titeket, úgy szeressétek ti is egymást” (Jn 13,34).</span>",
            "<span class=\"szidezet\">„Tiszteld atyádat és anyádat, hogy sokáig élj azon a földön, amelyet az Úr, a te Istened ad neked” (Kiv 20,12). <br /><span class=\"behuzas\">„És</span> engedelmeskedett nekik” (Lk 2,51). <br /><span class=\"behuzas\">Maga</span> az Úr Jézus is emlékeztetett „Isten parancsának” <a href=\"#lj3021\" name=\"ljl3021\"><span class=\"labjegylink\">[3021]</span></a>  jelentőségére. Az Apostol tanítja: „Gyermekek, engedelmeskedjetek szüleiteknek az Úrban, mert így van rendjén. Ez az első ígérettel egybekötött parancs: »Tiszteld apádat és anyádat, hogy boldog és hosszú életű légy a földön«.” (Ef 6,1–3) <a href=\"#lj3022\" name=\"ljl3022\"><span class=\"labjegylink\">[3022]</span></a>  </span>",
            "<span class=\"szidezet\">„Ne ölj!” (Kiv 20,13) <br /><span class=\"behuzas\">„Hallottátok,</span> hogy mondadott a régieknek: »Ne ölj! Aki öl, állítsák a törvényszék elé.« Én pedig azt mondom nektek: Már azt is állítsák a törvényszék elé, aki haragszik felebarátjára.” (Mt 5,21–22) </span>",
            "<span class=\"szidezet\">„Ne törj házasságot!”</h6></a> (Kiv 20,14) <a href=\"#lj3102\" name=\"ljl3102\"><span class=\"labjegylink\">[3102]<br /><span class=\"behuzas\">„Hallottátok,</span> hogy mondatott a régieknek: »Ne törj házasságot!« Én pedig mondom nektek, hogy aki bűnös vággyal asszonyra néz, szívében már házasságtörést követ el vele.” (Mt 5,27–28) </span>",
            "<span class=\"szidezet\">„Ne lopj!” (Kiv 20,15; Mt 19,18) <a href=\"#lj3166\" name=\"ljl3166\"><span class=\"labjegylink\">[3166]</span></a>  </span>",
            "<span class=\"szidezet\">„Ne szólj hamis tanúságot a felebarátod ellen!” (Kiv 20,16) <br /><span class=\"behuzas\">„Hallottátok,</span> hogy mondatott a régieknek: »Ne esküdjél hamisan, hanem tartsd meg az Úrnak tett esküdet!«” (Mt 5,33) </span>",
            "<span class=\"szidezet\">„Ne kívánd felebarátod házát: ne kívánd feleségét, szolgáját, szolgájóját, ökrét, szamarát, sem más egyebet, ami az övé.” (Kiv 20,17) <br /><span class=\"behuzas\">„Aki</span> bűnös vággyal asszonyra néz, szívében már házasságtörést követett el vele” (Mt 5,28). </span>",
            "<span class=\"szidezet\">„Ne kívánj semmit, ami a felebarátodé” (Kiv 20, 17). „Ne kívánd felebarátod házát, földjét, szolgáját, szolgálóját, ökrét, szamarát. Egyáltalán ne kívánj semmit, ami felebarátodé.” (MTörv 5,21) <br /><span class=\"behuzas\">„Ahol</span> a kincsed, ott a szíved is” (Mt 6,21). </span>",
            "<span class=\"szidezet\">„Számomra az imádság a szív dobbanása, egyszerű, ég felé küldött tekintet, a hála és a szeretet kiáltása mind a megpróbáltatás, mind az öröm idején.” <a href=\"#lj3314\" name=\"ljl3314\"><span class=\"labjegylink\">[3314]</span></a>  </span>"
    };

    private static final String szamozatlanTiszta[][] = {
            {"s1", "„Atyám, ... az örök élet az, hogy megismerjenek téged, az egyedül igaz Istent, és akit küldtél, Jézus Krisztust” (Jn 17,3). „Isten, a mi Üdvözítőnk ... azt akarja, hogy minden ember üdvözüljön és eljusson az igazság ismeretére” (1Tim 2,3–4). „Nem adatott más név az ég alatt az embereknek, amelyben üdvözülhetnének” (ApCsel 4,12), csak Jézus Neve."},
            {"k2", "Apostoli hitvallás Nicea–konstantinápolyi hitvallás  Hiszek egy Istenben, mindenható Atyában, mennynek és földnek Teremtőjében.Hiszek az egy Istenben, mindenható Atyában, mennynek és földnek, minden láthatónak és láthatatlannak Teremtőjében.És Jézus Krisztusban, az ő egyszülött Fiában, a mi Urunkban;Hiszek az egy Úrban, Jézus Krisztusban, Isten egyszülött Fiában, aki az Atyától született az idők kezdete előtt. Isten az Istentől, Világosság a Világosságtól, valóságos Isten a valóságos Istentől, született, de nem teremtmény, az Atyával egylényegű, és minden általa lett. Értünk, emberekért, a mi üdvösségünkért leszállott a mennyből. aki fogantatott Szentlélektől, született Szűz Máriától; szenvedett Poncius Pilátus alatt; megfeszítették, meghalt és eltemették. Alászállt a poklokra, harmadnapon feltámadt a halottak közül; fölment a mennybe, ott ül a mindenható Atyaisten jobbján; onnan jön el ítélni élőket és holtakat.Megtestesült a Szentlélek erejéből Szűz Máriától, és emberré lett. Poncius Pilátus alatt értünk keresztre feszítették, kínhalált szenvedett és eltemették.Harmadnapra föltámadott a halottak közül; az Írások szerint, fölment a mennybe, ott ül az Atyának jobbján, de újra eljön dicsőségben ítélni élőket és holtakat, és országának nem lesz vége.Hiszek Szentlélekben.Hiszek a Szentlélekben Urunkban és éltetőnkben, aki az Atyától és a Fiútól származik; akit éppúgy imádunk és dicsőítünk, mint az Atyát és a Fiút. Ő szólt a próféták szavával.Hiszem a katolikus Anyaszentegyházat, a szentek közösségét, a bűnök bocsánatát, a test föltámadását és az örök életet. Amen.Hiszek az egy, szent, katolikus és apostoli Anyaszentegyházban, vallom az egy keresztséget a bűnök bocsánatára, várom a holtak feltámadását és az eljövendő örök életet. Amen."},
            {"s3", "Akkor Mózes mondta Istennek: „Íme, én elmegyek Izrael fiaihoz, és mondom nekik: »Atyáitok Istene küldött engem hozzátok«. Ha mondják majd nekem: »Mi az ő neve?«, mit mondjak nekik?” Akkor Isten válaszolta Mózesnek: „Én vagyok aki vagyok.” Mondta: „Így mondd Izrael fiainak: »Aki vagyok« küldött engem hozzátok. (...) Ez az én nevem mindörökre, és ez az én emlékezetem nemzedékről nemzedékre.” (Kiv 3,13–15)"},
            {"k4", "„A búcsú Isten színe előtt a már megbocsátott bűnökért járó, ideigtartó büntetések elengedése, melyet a keresztény hívő, aki megfelelően fölkészült és teljesítette a kiszabott föltételeket, elnyer az Egyház segítségével, amely mint a megváltás szolgálója Krisztus és a szentek elégtételt nyújtó érdemeinek kincstárát hivatalosan kezeli és abban részesít.”  „A búcsú részleges vagy teljes, attól függően, hogy a bűnökért járó ideigtartó büntetéstől részlegesen vagy teljesen szabadít-e meg.”   „Minden hívő nyerhet búcsúkat (...) önmaga számára vagy az elhunytak javára.”"},
            {"s5", "Az emberi cselekedetek erkölcsisége függ: – a választott tárgytól; – a kitűzött céltól vagyis a szándéktól; – a cselekedet körülményeitől."},
            {"s6", "„A szentek közössége téged dicsőít, és amikor megkoronázod érdemeiket, a Te ajándékaidat koronázod meg.”"},
            {"k7", "Kivonulás 20,2–17.Második Törvénykönyv 5,6–21.Kateketikai formula Én vagyok az Úr, a te Istened, aki kivezettelek téged Egyiptom földjéről, a szolgaság házából. Ne legyenek idegen isteneid előttem. Ne csinálj magadnak faragott képet, vagy hasonmást arról, ami fent van az égben, vagy lenn a földön, vagy a vizekben, a föld alatt. Ne borulj le  ilyen képek előtt és ne tiszteld őket, mert Én az Úr, a te Istened, féltékeny Isten vagyok. Azoknak vétkét, akik gyűlölnek engem, megtorlom fiaikon, unokáikon és dédunokáikon, de ezredízig irgalmasságot gyakorlok azokkal, akik szeretnek, és megtartják parancsaimat. Én vagyok az Úr, a te Istened, aki kivezettelek téged Egyiptom földjéről, a szolgaság házából. Ne legyenek idegen isteneid a színem előtt.\"Én vagyok az Úr, a te Istened: Ne legyenek más isteneid előttem.Uradnak, Istenednek nevét ne vedd hiába, mert az Úr nem hagyja büntetlenül azt, aki a nevét hiába veszi.Uradnak, Istenednek nevét ne vedd hiába...Ne vedd hiába a te Uradnak, Istenednek nevét.Gondolj a szombatra és szenteld meg. Hat napig dolgozzál és végezd minden munkádat; a hetedik nap azonban az Úrnak, a te Istenednek szombatja; semmiféle munkát nem szabad végezned sem neked, sem fiadnak, sem lányodnak, sem szolgádnak, sem szolgálódnak, sem állatodnak, sem az idegennek, aki kapuidon belül tartózkodik. Az Úr ugyanis hat nap alatt teremtette az eget és a földet, a tengert és mindent, ami bennük van, a hetedik nap azonban megpihent. Ezért az Úr a szombatot megáldotta és megszentelte.Tartsd meg a szombatot, hogy megszenteld.Megemlékezzél arról, hogy az ünnepnapokat megszenteld.Tiszteld atyádat és anyádat, hogy sokáig élj azon a földön, amelyet az Úr, a te Istened ad neked.Tiszteld atyádat és anyádat.Tiszteld atyádat és anyádat.Ne ölj.Ne ölj.Ne ölj.Ne paráználkodjál.Ne paráználkodjál.Ne paráználkodjál.Ne lopj.Ne lopj.Ne lopj.Ne szólj hamis tanúságot felebarátod ellen.Ne szólj hamis tanúságot felebarátod ellen.Ne szólj hamis tanúságot felebarátod ellen.Ne kívánd felebarátod házát:Ne kívánd felebarátod feleségét.Ne kívánd feleségét.Ne kívánd feleségét, szolgáját, szolgálóját, ökrét, szamarát, sem más egyebet, ami az övé. Ne kívánd (...) semmijét, ami az övé. Ne kívánd a javait."},
            {"s8", "„Én vagyok az Úr, a te Istened, aki kivezettelek téged Egyiptom földjéről, a szolgaság házából. Ne legyenek idegen isteneid előttem. Ne csinálj magadnak faragott képet, vagy hasonmást arról, ami fent van az égben, vagy lenn a földön, vagy a vizekben, a föld alatt. Ne borulj le ilyen képek előtt és ne tiszteld őket.” (Kiv 20,2–5)  „Írva  van ugyanis: Uradat, Istenedet imádd, és csak neki szolgálj!” (Mt 4,10)"},
            {"s9", "„Ne vedd hiába a te Uradnak, Istenednek Nevét” (Kiv 20,7).  „Mondatott a régieknek: »Ne esküdjél hamisan« (...) Én pedig azt mondom nektek: Egyáltalán ne esküdjetek.” (Mt 5,33–34)"},
            {"s10", "„Gondolj a szombatra, és szenteld meg. Hat napig dolgozzál és végezd minden munkádat. A hetedik nap azonban az Úmak, a te Istenednek szombatja, ezért semmiféle munkát nem szabad végezned.” (Kiv 20,8– 10)  „A szombat van az emberért, nem az ember a szombatért. Az Emberfia ura a szombatnak is.” (Mk 2,27–28)"},
            {"s11", "„Ezt a napot az Úr Isten adta, ujjongjunk és vigadjunk rajta!” (Zsolt 118,24)"},
            {"s12", "Jézus így szólt tanítványaihoz: „Amint én szerettelek titeket, úgy szeressétek ti is egymást” (Jn 13,34)."},
            {"s13", "„Tiszteld atyádat és anyádat, hogy sokáig élj azon a földön, amelyet az Úr, a te Istened ad neked” (Kiv 20,12). „És engedelmeskedett nekik” (Lk 2,51). Maga az Úr Jézus is emlékeztetett „Isten parancsának”   jelentőségére. Az Apostol tanítja: „Gyermekek, engedelmeskedjetek szüleiteknek az Úrban, mert így van rendjén. Ez az első ígérettel egybekötött parancs: »Tiszteld apádat és anyádat, hogy boldog és hosszú életű légy a földön«.” (Ef 6,1–3)"},
            {"s14", "„Ne ölj!” (Kiv 20,13) „Hallottátok, hogy mondadott a régieknek: »Ne ölj! Aki öl, állítsák a törvényszék elé.« Én pedig azt mondom nektek: Már azt is állítsák a törvényszék elé, aki haragszik felebarátjára.” (Mt 5,21–22)"},
            {"s15", "„Ne törj házasságot!” (Kiv 20,14) „Hallottátok, hogy mondatott a régieknek: »Ne törj házasságot!« Én pedig mondom nektek, hogy aki bűnös vággyal asszonyra néz, szívében már házasságtörést követ el vele.” (Mt 5,27–28)"},
            {"s16", "„Ne lopj!” (Kiv 20,15; Mt 19,18)"},
            {"s17", "„Ne szólj hamis tanúságot a felebarátod ellen!” (Kiv 20,16) „Hallottátok, hogy mondatott a régieknek: »Ne esküdjél hamisan, hanem tartsd meg az Úrnak tett esküdet!«” (Mt 5,33)"},
            {"s18", "„Ne kívánd felebarátod házát: ne kívánd feleségét, szolgáját, szolgájóját, ökrét, szamarát, sem más egyebet, ami az övé.” (Kiv 20,17) „Aki bűnös vággyal asszonyra néz, szívében már házasságtörést követett el vele” (Mt 5,28)."},
            {"s19", "„Ne kívánj semmit, ami a felebarátodé” (Kiv 20, 17). „Ne kívánd felebarátod házát, földjét, szolgáját, szolgálóját, ökrét, szamarát. Egyáltalán ne kívánj semmit, ami felebarátodé.” (MTörv 5,21) „Ahol a kincsed, ott a szíved is” (Mt 6,21)."},
            {"s20", "„Számomra az imádság a szív dobbanása, egyszerű, ég felé küldött tekintet, a hála és a szeretet kiáltása mind a megpróbáltatás, mind az öröm idején.”"}
    };

}
