package hu.kek.Adatok;

import java.util.ArrayList;

/**
 * Created by Bence on 2017. 01. 26..
 */

public class AdatApostoli {

    public static ArrayList kereses (String eredeti) {
        eredeti = eredeti.toLowerCase();
        String keresendo = "(.*)"+eredeti+"(.*)";
        ArrayList<String[]> vissza = new ArrayList<>();
        String laetamurKicsi = laetamurTiszta.toLowerCase();
        String fideiKicsi = fideiTiszta.toLowerCase();
        if(laetamurKicsi.matches(keresendo)) {
            String szovegben = laetamurTiszta.substring(laetamurKicsi.split(eredeti)[0].length(), laetamurKicsi.split(eredeti)[0].length()+eredeti.length());
            vissza.add(new String[] {"a0", laetamurTiszta.replaceAll(szovegben, "_<span class=\"kiemel\">"+szovegben+"</span>_")});
        }
        if(fideiKicsi.matches(keresendo)) {
            String szovegben = fideiTiszta.substring(fideiKicsi.split(eredeti)[0].length(), fideiKicsi.split(eredeti)[0].length()+eredeti.length());
            vissza.add(new String[] {"a1", fideiTiszta.replaceAll(szovegben, "_<span class=\"kiemel\">"+szovegben+"</span>_")});
        }
        return vissza;
    }

    public static ArrayList szavasKereses (String eredeti) {
        eredeti = eredeti.toLowerCase();
        String keresendo = "(.*)[('„»\\-\\s]"+eredeti+"[\\s\\-«”').,!?:;](.*)";
        ArrayList<String[]> vissza = new ArrayList<>();
        String laetamurKicsi = laetamurTiszta.toLowerCase();
        String fideiKicsi = fideiTiszta.toLowerCase();
        if(laetamurKicsi.matches(keresendo)) {
            String szovegben = laetamurTiszta.substring(laetamurKicsi.split(eredeti)[0].length(), laetamurKicsi.split(eredeti)[0].length()+eredeti.length());
            vissza.add(new String[] {"a0", laetamurTiszta.replaceAll("[('„»\\-\\s]"+szovegben+"[\\s\\-«”').,!?:;]", "_<span class=\"kiemel\">$0</span>_")});
        }
        if(fideiKicsi.matches(keresendo)) {
            String szovegben = fideiTiszta.substring(fideiKicsi.split(eredeti)[0].length(), fideiKicsi.split(eredeti)[0].length()+eredeti.length());
            vissza.add(new String[] {"a1", fideiTiszta.replaceAll("[('„»\\-\\s]"+szovegben+"[\\s\\-«”').,!?:;]", "_<span class=\"kiemel\">$0</span>_")});
        }
        return vissza;
    }

    public static final String laetamur = "<p align=\"center\";><b>LAETAMUR MAGNOPERE</b><br />KEZDETŰ APOSTOLI LEVÉL<br /><br />" +
            "mely jóváhagyja és közzéteszi<br />A Katolikus Egyház Katekizmusának<br />latin editio typica-ját</p>" +
            "<p align=\"center\">A Főtisztelendő Bíboros Testvéreknek, Pátriárkáknak, Érsekeknek, Püspököknek, Papoknak, Diákonusoknak és Isten népe többi tagjának</p>" +
            "<p align=\"center\">JÁNOS PÁL PÜSPÖK<br />ISTEN SZOLGÁINAK SZOLGÁJA<br />ÖRÖK EMLÉKEZETÜL</p>" +
            "<p align=\"justify\";>Szerfölött örvendünk annak, hogy megjelent A Katolikus Egyház Katekizmusának latin mintakiadása, melyet jelen apostoli levelünkkel jóváhagyunk és közzéteszünk, s mely ezáltal az említett Katekizmus végleges szövege. Mintegy öt évvel azután történik ez, hogy 1992. október 11-én kibocsátottuk a Fidei depositum kezdetű apostoli konstitúciót, mely a II. Vatikáni Zsinat megnyitásának 30. évfordulóján a Katekizmus francia nyelvű első szövegét bevezette a világba.<br /><br />" +
            "Valamennyien örömmel állapíthattuk meg, hogy az elmúlt években többnyire mily kedvező fogadtatásban részesült e Katekizmus, s mily széles körben elterjedt, főként azokban a részegyházakban, melyek saját nyelvükre lefordították, hogy a különböző nyelvű közösségeknek szerte a földön rendelkezésére álljon. Ez bizonyítja, mennyire indokolt volt 1985-ben a rendkívüli Püspöki Szinodus kérése felénk, hogy készüljön el a Katekizmus, vagyis az egész katolikus hit- és erkölcstan foglalata.<br /><br />" +
            "A Bíborosok és Püspökök 1986-ban e célból létrehozott Tanácsának gyümölcseként a fent említett apostoli konstitúcióval jóváhagytuk és közzétettük a Katekizmust, mely teljes terjedelmében változatlanul hatályban marad és a jelen latin editio typica-val nyeri el végső formáját.<br /><br />" +
            "A jelen kiadást az Apostoli Szentszék különböző munkatársaiból álló Tanács készítette, melyet 1993-ban kifejezetten ezért hoztunk létre. E Tanács, melynek elnökévé főtisztelendő testvérünket, Joseph Ratzinger bíborost állítottuk, gondosan dolgozott a rábízott feladaton, különös figyelmet fordítva a sok javasolt javításra, melyek a Katekizmus megjelenése óta eltelt években a világ minden részéről és a különböző egyházi közösségektől érkeztek be.<br /><br />" +
            "A Katekizmus készítése során egészen nyilvánvalóvá vált és az egész földkerekségen, még a nem keresztények körében is sokféleképpen megnyilvánult a teljesen egyedülálló igény, mely megerősítette a Katekizmus rendeltetését, hogy a katolikus tanítás teljes és ép bemutatása legyen, melyből bárki megismerheti, hogy az Egyház mit hisz és ünnepel, hogyan él, és a mindennapjaiban miért imádkozik. Ugyanakkor nyilvánvalóvá vált a készséges akarat az együttműködésre azért, hogy a keresztény hitet, melynek alapvető és szükséges elemeit a Katekizmus tartalmazza, napjaink embere számára a lehető legalkalmasabb módon mutassuk be. A sok részegyház együttműködése hozta létre azt, amit az említett Fidei depositum apostoli konstitúcióban mondtunk: „ennyi hang egybecsengése kétségtelenül a hit „szimfóniája”'.<br /><br />" +
            "A Tanács ezek miatt is komolyan mérlegelte a benyújtott véleményeket, kérdésföltevésekkel pontosabbá tette, és ítéleteit jóváhagyásra átadta nekünk. Ezeket az ítéleteket, amennyiben hozzásegítenek, hogy a Katekizmus anyaga jobban megfeleljen a katolikus hitletéteménynek, illetve lehetővé teszik, hogy bizonyos hitigazságok a mai hitoktatás követelményeinek jobban megfelelő formát nyerjenek, elfogadtuk, és helyet kaptak e latin mintakiadásban. E kiadás tanítása hűségesen ismétli azt a kiadást, melyet az Egyháznak és a földkerekség embereinek 1992 decemberében átnyújtottunk. A ma nyilvánosságra hozott latin mintakiadás beteljesíti a Katekizmus 1986-ban megkezdett munkálatait, és szerencsésen teljesíti a Püspöki Szinodus említett rendkívüli ülésének kívánságát. Most tehát az Egyház kezében van egyetlen és örök apostoli hitének új és nagytekintélyű bemutatása, mely „az egyházi közösség számára érvényes és törvényes eszköz” és „a hit tanításának biztos szabálya”, továbbá „biztos és hiteles hivatkozási szöveg” (Fidei depositum, 4).<br /><br />" +
            "A katolikus hit és tanítás e világos és rendszerezett bemutatásában a hitoktatás abszolút biztos utat talál arra, hogy a keresztény üzenetet megújult buzgósággal adja át korunk minden egyes emberének. E kötetben minden hitoktató biztos támaszra lel, hogy a helyi egyházban közölni tudja a hit egyetlen és örök letéteményét, miközben a Szentlélek segítségével a keresztény misztérium csodálatos egységét összekapcsolni törekszik azok életkörülményeinek és szükségleteinek sokféleségével, akiknek az üzenet szól. Isten népében az egész hitoktatás új és bőséges ösztönzést nyerhet, ha jól használja és helyesen értékeli e zsinat utáni Katekizmust.<br /><br />" +
            "Mindez nagyobb jelentőséget nyer ma, a harmadik évezred küszöbén. Sürget ugyanis az evangelizációs feladat, hogy mindenki megismerhesse az evangéliumi üzenetet, elfogadhassa és növekedhessék „Krisztus nagykorúságának mértékére”. (Ef 4,13)<br /><br />" +
            "<span id=\"cucc\">Nyomatékosan buzdítjuk tehát Főtisztelendő Püspöktestvéreinket, akikre elsősorban bízzuk A Katolikus Egyház Katekizmusát, hogy a jelen mintakiadás alkalmával élve odaadóbbak legyenek a szöveg terjesztésében és készséges elfogadtatásában, s ajándékként adják át a rájuk bízott közösségeknek, melyek a hit kimeríthetetlen gazdagságát fedezhetik föl benne.<br /><br />" +
            "Bárcsak az Isten népét alkotók egybecsengő és egymást kiegészítő szolgálata terjesztené a Katekizmust, s bárcsak mindenki befogadná, hogy megerősödjék és a föld határáig terjedjen az a hívő egyetértés, melynek forrása és elve a Szentháromságos Egységben található.<br /><br />" +
            "Krisztus Anyjára, Máriára – kinek testestől-lelkestől való mennybe fölvételét ma együtt ünnepeljük – bízzuk ezen óhajunkat, melynek teljesedése minden ember lelki javára váljék.</p><br />" +
            "<p>Kelt Castel Gandolfóban, 1997. augusztus 15-én, pápaságunk 19. esztendejében.</p>";

    public static final String laetamurTiszta = "LAETAMUR MAGNOPERE KEZDETŰ APOSTOLI LEVÉL " +
            "mely jóváhagyja és közzéteszi A Katolikus Egyház Katekizmusának latin editio typica-ját " +
            "A Főtisztelendő Bíboros Testvéreknek, Pátriárkáknak, Érsekeknek, Püspököknek, Papoknak, Diákonusoknak és Isten népe többi tagjának " +
            "JÁNOS PÁL PÜSPÖK ISTEN SZOLGÁINAK SZOLGÁJA ÖRÖK EMLÉKEZETÜL " +
            "Szerfölött örvendünk annak, hogy megjelent A Katolikus Egyház Katekizmusának latin mintakiadása, melyet jelen apostoli levelünkkel jóváhagyunk és közzéteszünk, s mely ezáltal az említett Katekizmus végleges szövege. Mintegy öt évvel azután történik ez, hogy 1992. október 11-én kibocsátottuk a Fidei depositum kezdetű apostoli konstitúciót, mely a II. Vatikáni Zsinat megnyitásának 30. évfordulóján a Katekizmus francia nyelvű első szövegét bevezette a világba. " +
            "Valamennyien örömmel állapíthattuk meg, hogy az elmúlt években többnyire mily kedvező fogadtatásban részesült e Katekizmus, s mily széles körben elterjedt, főként azokban a részegyházakban, melyek saját nyelvükre lefordították, hogy a különböző nyelvű közösségeknek szerte a földön rendelkezésére álljon. Ez bizonyítja, mennyire indokolt volt 1985-ben a rendkívüli Püspöki Szinodus kérése felénk, hogy készüljön el a Katekizmus, vagyis az egész katolikus hit- és erkölcstan foglalata. " +
            "A Bíborosok és Püspökök 1986-ban e célból létrehozott Tanácsának gyümölcseként a fent említett apostoli konstitúcióval jóváhagytuk és közzétettük a Katekizmust, mely teljes terjedelmében változatlanul hatályban marad és a jelen latin editio typica-val nyeri el végső formáját. " +
            "A jelen kiadást az Apostoli Szentszék különböző munkatársaiból álló Tanács készítette, melyet 1993-ban kifejezetten ezért hoztunk létre. E Tanács, melynek elnökévé főtisztelendő testvérünket, Joseph Ratzinger bíborost állítottuk, gondosan dolgozott a rábízott feladaton, különös figyelmet fordítva a sok javasolt javításra, melyek a Katekizmus megjelenése óta eltelt években a világ minden részéről és a különböző egyházi közösségektől érkeztek be. " +
            "A Katekizmus készítése során egészen nyilvánvalóvá vált és az egész földkerekségen, még a nem keresztények körében is sokféleképpen megnyilvánult a teljesen egyedülálló igény, mely megerősítette a Katekizmus rendeltetését, hogy a katolikus tanítás teljes és ép bemutatása legyen, melyből bárki megismerheti, hogy az Egyház mit hisz és ünnepel, hogyan él, és a mindennapjaiban miért imádkozik. Ugyanakkor nyilvánvalóvá vált a készséges akarat az együttműködésre azért, hogy a keresztény hitet, melynek alapvető és szükséges elemeit a Katekizmus tartalmazza, napjaink embere számára a lehető legalkalmasabb módon mutassuk be. A sok részegyház együttműködése hozta létre azt, amit az említett Fidei depositum apostoli konstitúcióban mondtunk: „ennyi hang egybecsengése kétségtelenül a hit „szimfóniája”'. " +
            "A Tanács ezek miatt is komolyan mérlegelte a benyújtott véleményeket, kérdésföltevésekkel pontosabbá tette, és ítéleteit jóváhagyásra átadta nekünk. Ezeket az ítéleteket, amennyiben hozzásegítenek, hogy a Katekizmus anyaga jobban megfeleljen a katolikus hitletéteménynek, illetve lehetővé teszik, hogy bizonyos hitigazságok a mai hitoktatás követelményeinek jobban megfelelő formát nyerjenek, elfogadtuk, és helyet kaptak e latin mintakiadásban. E kiadás tanítása hűségesen ismétli azt a kiadást, melyet az Egyháznak és a földkerekség embereinek 1992 decemberében átnyújtottunk. A ma nyilvánosságra hozott latin mintakiadás beteljesíti a Katekizmus 1986-ban megkezdett munkálatait, és szerencsésen teljesíti a Püspöki Szinodus említett rendkívüli ülésének kívánságát. Most tehát az Egyház kezében van egyetlen és örök apostoli hitének új és nagytekintélyű bemutatása, mely „az egyházi közösség számára érvényes és törvényes eszköz” és „a hit tanításának biztos szabálya”, továbbá „biztos és hiteles hivatkozási szöveg” (Fidei depositum, 4). " +
            "A katolikus hit és tanítás e világos és rendszerezett bemutatásában a hitoktatás abszolút biztos utat talál arra, hogy a keresztény üzenetet megújult buzgósággal adja át korunk minden egyes emberének. E kötetben minden hitoktató biztos támaszra lel, hogy a helyi egyházban közölni tudja a hit egyetlen és örök letéteményét, miközben a Szentlélek segítségével a keresztény misztérium csodálatos egységét összekapcsolni törekszik azok életkörülményeinek és szükségleteinek sokféleségével, akiknek az üzenet szól. Isten népében az egész hitoktatás új és bőséges ösztönzést nyerhet, ha jól használja és helyesen értékeli e zsinat utáni Katekizmust. " +
            "Mindez nagyobb jelentőséget nyer ma, a harmadik évezred küszöbén. Sürget ugyanis az evangelizációs feladat, hogy mindenki megismerhesse az evangéliumi üzenetet, elfogadhassa és növekedhessék „Krisztus nagykorúságának mértékére”. (Ef 4,13) " +
            "Nyomatékosan buzdítjuk tehát Főtisztelendő Püspöktestvéreinket, akikre elsősorban bízzuk A Katolikus Egyház Katekizmusát, hogy a jelen mintakiadás alkalmával élve odaadóbbak legyenek a szöveg terjesztésében és készséges elfogadtatásában, s ajándékként adják át a rájuk bízott közösségeknek, melyek a hit kimeríthetetlen gazdagságát fedezhetik föl benne. " +
            "Bárcsak az Isten népét alkotók egybecsengő és egymást kiegészítő szolgálata terjesztené a Katekizmust, s bárcsak mindenki befogadná, hogy megerősödjék és a föld határáig terjedjen az a hívő egyetértés, melynek forrása és elve a Szentháromságos Egységben található. " +
            "Krisztus Anyjára, Máriára – kinek testestől-lelkestől való mennybe fölvételét ma együtt ünnepeljük – bízzuk ezen óhajunkat, melynek teljesedése minden ember lelki javára váljék. " +
            "Kelt Castel Gandolfóban, 1997. augusztus 15-én, pápaságunk 19. esztendejében.";

    public static final String fidei = "<p align=\"center\";><b>FIDEI DEPOSITUM KEZDETŰ</b><br />APOSTOLI KONSTITÚCIÓ<br /><br />mely közzéteszi<br />A Katolikus Egyház Katekizmusát<br />a II. Vatikáni Egyetemes Zsinat után</p>" +
            "<p align=\"center\">A Főtisztelendő Bíboros Testvéreknek, Pátriárkáknak, Érsekeknek, Püspököknek, Papoknak, Diákonusoknak és Isten népe többi tagjának</p>" +
            "<p align=\"center\">JÁNOS PÁL PÜSPÖK<br />ISTEN SZOLGÁINAK SZOLGÁJA<br />ÖRÖK EMLÉKEZETÜL</p>" +
            "<p align=\"justify\";>Bevezetés<br />" +
            "A HITLETÉTEMÉNY őrzését az Úr adta Egyháza feladatául, s az Egyház e feladatot minden időben teljesíti. A II. Vatikáni Zsinatnak, melyet boldogemlékű elődünk, XXIII. János pápa harminc évvel ezelőtt nyitott meg, szándéka és óhaja arra irányult, hogy megfelelő megvilágításba kerüljön az Egyház apostoli és lelkipásztori küldetése, és így az evangéliumi igazság ragyogó fénye minden embert serkentsen Krisztus mindent fölülmúló szeretetének keresésére és elfogadására (vö. Ef 3,19).<br /><br />" +
            "XXIII. János pápa a zsinat fő feladatául azt adta, hogy a keresztény tanítás drága kincsét gondosabban őrizze és jobban tárja föl, hogy hozzáférhetőbb legyen a Krisztus-hívők és minden jóakaratú ember számára. Ezért a zsinatnak elsősorban nem a kor tévedéseit kellett elítélnie, hanem a hit tanítása erejének és szépségének világos bemutatására kellett törekednie. „E zsinat fényétől megvilágítva – mondta ő – az Egyház gyarapodni fog, miként bízunk benne, lelki javakban, és a zsinatból új erőt merítve félelem nélkül fog a jövőbe tekinteni.” A mi dolgunk, hogy „serényen, félelem nélkül fogjunk a munkához, melyet korunk megkíván, hogy folytassuk az utat, melyet az Egyház immár húsz évszázada jár.” <a href=\"#lj1\" name=\"ljl1\"><span class=\"labjegylink\">[1]</span></a><br /><br />" +
            "A zsinati atyák Isten segítségével, négyéves munkával a tanításnak és a lelkipásztori irányelveknek nem megvetendő summáját tudták kidolgozni az egész Egyház számára. Lelkipásztorok és Krisztus-hívők segítséget kapnak benne „a gondolkodás, a cselekvés, az erkölcsök és az erkölcsi erő, az öröm és a remény azon megújulásához, melyet a zsinat hőn óhajtott”. <a href=\"#lj2\" name=\"ljl2\"><span class=\"labjegylink\">[2]</span></a><br /><br />" +
            "A zsinat befejezése után sem szűnik meg serkenteni az egyházi életet. 1985-ben megállapíthattam: „Számomra, akinek megadatott az a különös kegyelem, hogy részt vehettem és aktívan közreműködhettem a zsinat munkájában, a II. Vatikáni Zsinat mindig, de főként pápaságom éveiben, egész lelkipásztori tevékenységem számára maradandó hivatkozási pont, és tudatosan törekedtem arra, hogy útmutatásait konkrétan és pontosan alkalmazzam minden részegyház és az egész Egyház számára. E forráshoz mindig vissza kell térnünk.” <a href=\"#lj3\" name=\"ljl3\"><span class=\"labjegylink\">[3]</span></a><br /><br />" +
            "Ebben a szellemben hívtam össze 1985. január 25-én a rendkívüli Püspöki Szinodust a zsinat befejezésének huszadik évfordulója alkalmából. E szinodus célja az volt, hogy ünnepelje a II. Vatikáni Zsinat kegyelmeit és lelki gyümölcseit, s hogy elmélyítse tanítását, hogy ezáltal az összes Krisztus-hívő jobban magáévá tehesse, s ismerete és alkalmazása szélesebb körű legyen.<br /><br />" +
            "Ilyen körülmények között nyilvánították ki a szinodusi atyák: „Egyhangúlag kívánjuk egy az egész katolikus hit- és erkölcstant összefoglaló Katekizmus, illetve kompendium elkészítését, hogy hivatkozási pont legyen a különféle régiókban szerkesztendő Katekizmusok, illetve kompendiumok számára. A tanítás bemutatásának biblikusnak és liturgikusnak kell lennie, az igaz tanítást kell nyújtania, ugyanakkor illeszkednie kell a mai élethez.” <a href=\"#lj4\" name=\"ljl4\"><span class=\"labjegylink\">[4]</span></a> A szinodus befejeztével magamévá tettem ezt a kívánságot, mert véleményem szerint „teljesen megfelelt az egyetemes Egyház és a részegyházak valós szükségletének”. <a href=\"#lj5\" name=\"ljl5\"><span class=\"labjegylink\">[5]</span></a><br /><br /> Ezért teljes szívből hálát adok az Úrnak ezen a napon, amikor fölajánlhatom az egyetemes Egyháznak A Katolikus Egyház Katekizmusát, mely „hivatkozási szöveg”a hit élő forrásaiból megújult Katekizmus számára!<br /><br />" +
            "A liturgia megújítása, a latin Egyház kánonjogának és a Keleti Katolikus Egyházak normáinak új kodifikációja után e Katekizmus jelentős mértékben hozzá fog járulni az egész Egyház életének megújulásához, miként ezt a II. Vatikáni Zsinat akarta és elindította.<br /><br />" +
            "A könyv előkészítésének útja és szelleme A Katolikus Egyház Katekizmusa igen széleskörű együttműködés gyümölcse: lelkiismeretes nyitottság és elkötelezett lelkesedés szellemében hatéves intenzív munka eredménye.<br /><br />" +
            "1986-ban Joseph Ratzinger bíboros vezetése alatt egy bíborosokból és püspökökből álló, tizenkét tagú bizottságra bíztam a feladatot, hogy készítsék elő a szinodusi atyák által óhajtott Katekizmus tervezetét. A bizottságot egy megyéspüspökökből, valamint a teológia és a katekézis szakértőiből álló, hét tagú albizottság segítette munkájában.<br /><br />" +
            "A bizottság, melynek az volt a feladata, hogy szabályokat javasoljon a munka folyamatához és felügyelje azt, figyelemmel kísérte a kilenc egymásutáni változat szerkesztésének minden lépését. A szerkesztőbizottság feladatának megfelelően vállalta a felelősséget, hogy megírja a szöveget, és a bizottság által kívánt változtatásokat bedolgozza, illetve számos teológus, szentírásmagyarázó, katekéta, s mindenekelőtt a világegyház püspökeinek megjegyzéseit figyelembe véve javítsa a szöveget. E szerkesztőbizottság nagy gonddal vetette össze a különböző véleményeket, ezáltal a szöveg gazdagabb lett, s biztosítani lehetett egységét és egyöntetűségét.<br /><br />" +
            "A tervezetet az összes katolikus püspök, püspöki konferenciáik, illetve szinodusaik, továbbá teológiai és kateketikai intézetek széles körben véleményezték. Egészében nagyon kedvező fogadtatásra talált a püspököknél, és joggal állapítható meg, hogy ez a Katekizmus a Katolikus Egyház egész püspöki kollégiuma együttműködésének gyümölcse. A püspökök nagylelkűen fogadták fölhívásomat, hogy vállaljanak részfelelősséget e kezdeményezésben, mely oly közelről érinti az egyházi életet. A válasz mély örömet ébreszt bennem, mert ennyi hang egybecsengése kétségtelenül a hit „szimfóniája”. E Katekizmus létrehozása mindezen felül mutatja a püspökség kollegiális természetét: az Egyház katolicitását tanúsítja.<br /><br />Az anyag felosztása<br />A Katekizmusnak hűségesen és szerves egységben kell bemutatnia mind a Szentírás, az Egyház élő hagyománya és a hiteles Tanítóhivatal tanítását, mind az egyházatyák és a szent férfiak és nők lelki örökségét, hogy a keresztény misztériumokat jobban megismertesse, és Isten népe hitét újjáélessze. Figyelemmel kell lennie a tanfejlődésre, melyet a Szentlélek az idők folyamán az Egyháznak adott. Segítséget is kell nyújtania azáltal, hogy a hit fényével megvilágítja az új élethelyzeteket és problémákat, melyek a múltban még nem merültek föl.<br /><br />A Katekizmus tehát újat és régit fog előhozni (vö. Mt 13,52), mert a hit mindig ugyanaz, s ugyanakkor mindig új fény forrása.<br /><br />A Katolikus Egyház Katekizmusa, hogy megfeleljen e kettős követelménynek, egyrészt átveszi az anyag elrendezésének „régi” hagyományát, melyet már Szent V. Pius pápa Katekizmusa követett, és anyagát négy részre osztja: Hitvallás; a szent Liturgia, melynek első részét a szentségek alkotják; a keresztény cselekvésmód, mely a Tízparancsolattal kezdődik; és végül a keresztény imádság. Másrészt az anyagot gyakran „új” módon mutatja be, hogy választ adjon korunk kérdéseire.<br /><br />" +
            "A négy rész kapcsolódik egymáshoz: a hit tárgya a keresztény misztérium (első rész); ugyanezt ünnepeljük és kapjuk a liturgikus cselekményekben (második rész); e misztérium jelen van, hogy Isten gyermekeit cselekvésükben megvilágítsa és támogassa (harmadik rész); ez alapozza meg imádságunkat, melynek kiváltságos formája a „Miatyánk”, és tárgya kérő, dicsőítő és közbenjáró imádságainknak<br />" +
            "(negyedik rész).<br /><br />" +
            "A liturgia maga imádság; a hitvallás megtalálta megfelelő helyét az istentisztelet ünneplésében. A kegyelem, a szentségek gyümölcse a keresztény tevékenység mással nem helyettesíthető föltétele, épp úgy, mint ahogyan az Egyház liturgiájában való részvétel megköveteli a hitet. Ha azonban a hit nem nyilvánul meg cselekedetekben, halott (vö. Jak 2,14–26), és nem teremhet gyümölcsöt az örök életre.<br /><br />" +
            "A Katolikus Egyház Katekizmusát olvasva fölfoghatjuk Isten misztériumának csodálatos egységét, mely magában foglalja Isten üdvözítő tervét éppen úgy, mint Jézus Krisztus központi szerepét, aki Isten egyszülött Fia, az Atya küldötte, s a Szentlélek erejéből a Boldogságos Szűz Mária méhében emberré lett, hogy Üdvözítőnk legyen. Meghalt és föltámadott Üdvözítőnk mindig jelen van Egyházában, különösen a szentségekben. Ô a hit forrása, a keresztény cselekvés példaképe és imádságunk Tanítómestere.<br /><br />" +
            "A szöveg tanbeli értéke<br />" +
            "A Katolikus Egyház Katekizmusa, melyet 1992. június 25-én jóváhagytam és közzétételét apostoli hivatalom erejéből ma elrendelem, a katolikus Egyház – a Szentírás, az apostoli hagyomány és az egyházi Tanítóhivatal által igazolt és megvilágított – hitének és tanításának bemutatása. E Katekizmust a hit tanításának erős szabályává, ebből következően az egyházi közösség hatékony és törvényes eszközévé nyilvánítom. Bárcsak elősegítené a megújulást, melyre a Szentlélek szüntelenül hívja az Egyházat, Krisztus Testét az árnyéktalan világosság országa felé vezető úton!<br /><br />" +
            "A Katolikus Egyház Katekizmusát jóváhagyni és közzétenni annak a szolgálatnak része, melyet Péter utóda nyújtani akar a Szent Katolikus Egyháznak, a Római Apostoli Székkel közösségben és békében élő minden részegyháznak: tudniillik támogatni és erősíteni akarja az Úr Jézus minden tanítványa hitét (vö. Lk 22,32), és ezáltal megszilárdítani az egység kötelékét ugyanabban az apostoli hitben.<br /><br />" +
            "Kérem ezért az Egyház pásztorait és a Krisztus-hívőket, hogy e Katekizmust a közösség szellemében fogadják, és gondosan használják küldetésük teljesítésekor, amikor hirdetik az evangéliumot és az evangélium szerinti életre buzdítanak. E Katekizmust úgy adom át nekik, hogy a katolikus tanítás előadásakor, s különösképpen a helyi Katekizmusok kidolgozásánál biztos és hiteles hivatkozási szöveg legyen. Ugyanakkor átadom minden Krisztus-hívőnek, akik szeretnék elmélyíteni az üdvösség kimeríthetetlen gazdagságának ismereteit (vö. Jn 8,32). Továbbá szolgáljon támaszul az ökumenikus törekvéseknek – melyek minden keresztény egység utáni szent vágyát fejezik ki – azáltal, hogy pontosan bemutatja a katolikus hit tartalmát és harmonikus, belső egységét. Végül ajánlom A Katolikus Egyház Katekizmusát minden egyes embernek, aki reménységünk alapja után kérdez (vö. 1Pt 3,15) és szeretné megismerni, hogy mit hisz a Katolikus Egyház.<br /><br />" +
            "Ez a Katekizmus nem akarja helyettesíteni az egyházi hatóságok, a megyéspüspökök vagy a püspöki konferenciák által szabályosan elfogadott helyi Katekizmusokat, főként, ha ezeket az Apostoli Szék jóváhagyta. Arra van rendelve, hogy bátorítsa és segítse új helyi Katekizmusok elkészítését, melyek figyelemmel vannak a különféle helyzetekre és kulturális adottságokra, ugyanakkor gondosan őrzik a hit egységét és a katolikus tanítás iránti hűséget.<br /><br />" +
            "Zárószó<br />" +
            "E dokumentum végén, mely közzéteszi A Katolikus Egyház Katekizmusát, kérem a Boldogságos Szűz Máriát, a megtestesült Ige Anyját és az Egyház Anyját, támogassa hathatós közbenjárásával az egész Egyház kateketikai szolgálatát minden fokon most, amikor az Egyház fölszólítást kapott az új evangelizációra. Bárcsak az igaz hit világossága megszabadítaná az embereket a tudatlanságtól és a bűn szolgaságától, hogy elvezesse őket az egyetlen e névre méltó szabadságra (vö. Jn 8,32), tudniillik a Jézus Krisztusban való, a Szentlélek által irányított élet szabadságára itt a földön és a mennyek országában, Isten színről-színre látásának teljes boldogságában (vö. 1Kor 13,12; 2Kor 5,6–8)!<br /></p><br />" +
            "<p>Kiadatott 1992. október 11-én, a második Vatikáni Zsinat megnyitásának harmincadik évfordulóján, pápaságom tizennegyedik évében.</p>";

    public static final String fideiTiszta = "FIDEI DEPOSITUM KEZDETŰ APOSTOLI KONSTITÚCIÓ  mely közzéteszi A Katolikus Egyház Katekizmusát a II. Vatikáni Egyetemes Zsinat után " +
            "A Főtisztelendő Bíboros Testvéreknek, Pátriárkáknak, Érsekeknek, Püspököknek, Papoknak, Diákonusoknak és Isten népe többi tagjának " +
            "JÁNOS PÁL PÜSPÖK ISTEN SZOLGÁINAK SZOLGÁJA ÖRÖK EMLÉKEZETÜL Bevezetés " +
            "A HITLETÉTEMÉNY őrzését az Úr adta Egyháza feladatául, s az Egyház e feladatot minden időben teljesíti. A II. Vatikáni Zsinatnak, melyet boldogemlékű elődünk, XXIII. János pápa harminc évvel ezelőtt nyitott meg, szándéka és óhaja arra irányult, hogy megfelelő megvilágításba kerüljön az Egyház apostoli és lelkipásztori küldetése, és így az evangéliumi igazság ragyogó fénye minden embert serkentsen Krisztus mindent fölülmúló szeretetének keresésére és elfogadására (vö. Ef 3,19). " +
            "XXIII. János pápa a zsinat fő feladatául azt adta, hogy a keresztény tanítás drága kincsét gondosabban őrizze és jobban tárja föl, hogy hozzáférhetőbb legyen a Krisztus-hívők és minden jóakaratú ember számára. Ezért a zsinatnak elsősorban nem a kor tévedéseit kellett elítélnie, hanem a hit tanítása erejének és szépségének világos bemutatására kellett törekednie. „E zsinat fényétől megvilágítva – mondta ő – az Egyház gyarapodni fog, miként bízunk benne, lelki javakban, és a zsinatból új erőt merítve félelem nélkül fog a jövőbe tekinteni.” A mi dolgunk, hogy „serényen, félelem nélkül fogjunk a munkához, melyet korunk megkíván, hogy folytassuk az utat, melyet az Egyház immár húsz évszázada jár.” " +
            "A zsinati atyák Isten segítségével, négyéves munkával a tanításnak és a lelkipásztori irányelveknek nem megvetendő summáját tudták kidolgozni az egész Egyház számára. Lelkipásztorok és Krisztus-hívők segítséget kapnak benne „a gondolkodás, a cselekvés, az erkölcsök és az erkölcsi erő, az öröm és a remény azon megújulásához, melyet a zsinat hőn óhajtott”. " +
            "A zsinat befejezése után sem szűnik meg serkenteni az egyházi életet. 1985-ben megállapíthattam: „Számomra, akinek megadatott az a különös kegyelem, hogy részt vehettem és aktívan közreműködhettem a zsinat munkájában, a II. Vatikáni Zsinat mindig, de főként pápaságom éveiben, egész lelkipásztori tevékenységem számára maradandó hivatkozási pont, és tudatosan törekedtem arra, hogy útmutatásait konkrétan és pontosan alkalmazzam minden részegyház és az egész Egyház számára. E forráshoz mindig vissza kell térnünk.” " +
            "Ebben a szellemben hívtam össze 1985. január 25-én a rendkívüli Püspöki Szinodust a zsinat befejezésének huszadik évfordulója alkalmából. E szinodus célja az volt, hogy ünnepelje a II. Vatikáni Zsinat kegyelmeit és lelki gyümölcseit, s hogy elmélyítse tanítását, hogy ezáltal az összes Krisztus-hívő jobban magáévá tehesse, s ismerete és alkalmazása szélesebb körű legyen. " +
            "Ilyen körülmények között nyilvánították ki a szinodusi atyák: „Egyhangúlag kívánjuk egy az egész katolikus hit- és erkölcstant összefoglaló Katekizmus, illetve kompendium elkészítését, hogy hivatkozási pont legyen a különféle régiókban szerkesztendő Katekizmusok, illetve kompendiumok számára. A tanítás bemutatásának biblikusnak és liturgikusnak kell lennie, az igaz tanítást kell nyújtania, ugyanakkor illeszkednie kell a mai élethez.” A szinodus befejeztével magamévá tettem ezt a kívánságot, mert véleményem szerint „teljesen megfelelt az egyetemes Egyház és a részegyházak valós szükségletének”. Ezért teljes szívből hálát adok az Úrnak ezen a napon, amikor fölajánlhatom az egyetemes Egyháznak A Katolikus Egyház Katekizmusát, mely „hivatkozási szöveg”a hit élő forrásaiból megújult Katekizmus számára! " +
            "A liturgia megújítása, a latin Egyház kánonjogának és a Keleti Katolikus Egyházak normáinak új kodifikációja után e Katekizmus jelentős mértékben hozzá fog járulni az egész Egyház életének megújulásához, miként ezt a II. Vatikáni Zsinat akarta és elindította. " +
            "A könyv előkészítésének útja és szelleme A Katolikus Egyház Katekizmusa igen széleskörű együttműködés gyümölcse: lelkiismeretes nyitottság és elkötelezett lelkesedés szellemében hatéves intenzív munka eredménye. " +
            "1986-ban Joseph Ratzinger bíboros vezetése alatt egy bíborosokból és püspökökből álló, tizenkét tagú bizottságra bíztam a feladatot, hogy készítsék elő a szinodusi atyák által óhajtott Katekizmus tervezetét. A bizottságot egy megyéspüspökökből, valamint a teológia és a katekézis szakértőiből álló, hét tagú albizottság segítette munkájában. " +
            "A bizottság, melynek az volt a feladata, hogy szabályokat javasoljon a munka folyamatához és felügyelje azt, figyelemmel kísérte a kilenc egymásutáni változat szerkesztésének minden lépését. A szerkesztőbizottság feladatának megfelelően vállalta a felelősséget, hogy megírja a szöveget, és a bizottság által kívánt változtatásokat bedolgozza, illetve számos teológus, szentírásmagyarázó, katekéta, s mindenekelőtt a világegyház püspökeinek megjegyzéseit figyelembe véve javítsa a szöveget. E szerkesztőbizottság nagy gonddal vetette össze a különböző véleményeket, ezáltal a szöveg gazdagabb lett, s biztosítani lehetett egységét és egyöntetűségét. " +
            "A tervezetet az összes katolikus püspök, püspöki konferenciáik, illetve szinodusaik, továbbá teológiai és kateketikai intézetek széles körben véleményezték. Egészében nagyon kedvező fogadtatásra talált a püspököknél, és joggal állapítható meg, hogy ez a Katekizmus a Katolikus Egyház egész püspöki kollégiuma együttműködésének gyümölcse. A püspökök nagylelkűen fogadták fölhívásomat, hogy vállaljanak részfelelősséget e kezdeményezésben, mely oly közelről érinti az egyházi életet. A válasz mély örömet ébreszt bennem, mert ennyi hang egybecsengése kétségtelenül a hit „szimfóniája”. E Katekizmus létrehozása mindezen felül mutatja a püspökség kollegiális természetét: az Egyház katolicitását tanúsítja.  Az anyag felosztása A Katekizmusnak hűségesen és szerves egységben kell bemutatnia mind a Szentírás, az Egyház élő hagyománya és a hiteles Tanítóhivatal tanítását, mind az egyházatyák és a szent férfiak és nők lelki örökségét, hogy a keresztény misztériumokat jobban megismertesse, és Isten népe hitét újjáélessze. Figyelemmel kell lennie a tanfejlődésre, melyet a Szentlélek az idők folyamán az Egyháznak adott. Segítséget is kell nyújtania azáltal, hogy a hit fényével megvilágítja az új élethelyzeteket és problémákat, melyek a múltban még nem merültek föl.  A Katekizmus tehát újat és régit fog előhozni (vö. Mt 13,52), mert a hit mindig ugyanaz, s ugyanakkor mindig új fény forrása.  A Katolikus Egyház Katekizmusa, hogy megfeleljen e kettős követelménynek, egyrészt átveszi az anyag elrendezésének „régi” hagyományát, melyet már Szent V. Pius pápa Katekizmusa követett, és anyagát négy részre osztja: Hitvallás; a szent Liturgia, melynek első részét a szentségek alkotják; a keresztény cselekvésmód, mely a Tízparancsolattal kezdődik; és végül a keresztény imádság. Másrészt az anyagot gyakran „új” módon mutatja be, hogy választ adjon korunk kérdéseire. " +
            "A négy rész kapcsolódik egymáshoz: a hit tárgya a keresztény misztérium (első rész); ugyanezt ünnepeljük és kapjuk a liturgikus cselekményekben (második rész); e misztérium jelen van, hogy Isten gyermekeit cselekvésükben megvilágítsa és támogassa (harmadik rész); ez alapozza meg imádságunkat, melynek kiváltságos formája a „Miatyánk”, és tárgya kérő, dicsőítő és közbenjáró imádságainknak " +
            "(negyedik rész). A liturgia maga imádság; a hitvallás megtalálta megfelelő helyét az istentisztelet ünneplésében. A kegyelem, a szentségek gyümölcse a keresztény tevékenység mással nem helyettesíthető föltétele, épp úgy, mint ahogyan az Egyház liturgiájában való részvétel megköveteli a hitet. Ha azonban a hit nem nyilvánul meg cselekedetekben, halott (vö. Jak 2,14–26), és nem teremhet gyümölcsöt az örök életre. " +
            "A Katolikus Egyház Katekizmusát olvasva fölfoghatjuk Isten misztériumának csodálatos egységét, mely magában foglalja Isten üdvözítő tervét éppen úgy, mint Jézus Krisztus központi szerepét, aki Isten egyszülött Fia, az Atya küldötte, s a Szentlélek erejéből a Boldogságos Szűz Mária méhében emberré lett, hogy Üdvözítőnk legyen. Meghalt és föltámadott Üdvözítőnk mindig jelen van Egyházában, különösen a szentségekben. Ô a hit forrása, a keresztény cselekvés példaképe és imádságunk Tanítómestere. " +
            "A szöveg tanbeli értéke Katolikus Egyház Katekizmusa, melyet 1992. június 25-én jóváhagytam és közzétételét apostoli hivatalom erejéből ma elrendelem, a katolikus Egyház – a Szentírás, az apostoli hagyomány és az egyházi Tanítóhivatal által igazolt és megvilágított – hitének és tanításának bemutatása. E Katekizmust a hit tanításának erős szabályává, ebből következően az egyházi közösség hatékony és törvényes eszközévé nyilvánítom. Bárcsak elősegítené a megújulást, melyre a Szentlélek szüntelenül hívja az Egyházat, Krisztus Testét az árnyéktalan világosság országa felé vezető úton! " +
            "A Katolikus Egyház Katekizmusát jóváhagyni és közzétenni annak a szolgálatnak része, melyet Péter utóda nyújtani akar a Szent Katolikus Egyháznak, a Római Apostoli Székkel közösségben és békében élő minden részegyháznak: tudniillik támogatni és erősíteni akarja az Úr Jézus minden tanítványa hitét (vö. Lk 22,32), és ezáltal megszilárdítani az egység kötelékét ugyanabban az apostoli hitben. " +
            "Kérem ezért az Egyház pásztorait és a Krisztus-hívőket, hogy e Katekizmust a közösség szellemében fogadják, és gondosan használják küldetésük teljesítésekor, amikor hirdetik az evangéliumot és az evangélium szerinti életre buzdítanak. E Katekizmust úgy adom át nekik, hogy a katolikus tanítás előadásakor, s különösképpen a helyi Katekizmusok kidolgozásánál biztos és hiteles hivatkozási szöveg legyen. Ugyanakkor átadom minden Krisztus-hívőnek, akik szeretnék elmélyíteni az üdvösség kimeríthetetlen gazdagságának ismereteit (vö. Jn 8,32). Továbbá szolgáljon támaszul az ökumenikus törekvéseknek – melyek minden keresztény egység utáni szent vágyát fejezik ki – azáltal, hogy pontosan bemutatja a katolikus hit tartalmát és harmonikus, belső egységét. Végül ajánlom A Katolikus Egyház Katekizmusát minden egyes embernek, aki reménységünk alapja után kérdez (vö. 1Pt 3,15) és szeretné megismerni, hogy mit hisz a Katolikus Egyház. " +
            "Ez a Katekizmus nem akarja helyettesíteni az egyházi hatóságok, a megyéspüspökök vagy a püspöki konferenciák által szabályosan elfogadott helyi Katekizmusokat, főként, ha ezeket az Apostoli Szék jóváhagyta. Arra van rendelve, hogy bátorítsa és segítse új helyi Katekizmusok elkészítését, melyek figyelemmel vannak a különféle helyzetekre és kulturális adottságokra, ugyanakkor gondosan őrzik a hit egységét és a katolikus tanítás iránti hűséget. " +
            "Zárószó " +
            "E dokumentum végén, mely közzéteszi A Katolikus Egyház Katekizmusát, kérem a Boldogságos Szűz Máriát, a megtestesült Ige Anyját és az Egyház Anyját, támogassa hathatós közbenjárásával az egész Egyház kateketikai szolgálatát minden fokon most, amikor az Egyház fölszólítást kapott az új evangelizációra. Bárcsak az igaz hit világossága megszabadítaná az embereket a tudatlanságtól és a bűn szolgaságától, hogy elvezesse őket az egyetlen e névre méltó szabadságra (vö. Jn 8,32), tudniillik a Jézus Krisztusban való, a Szentlélek által irányított élet szabadságára itt a földön és a mennyek országában, Isten színről-színre látásának teljes boldogságában (vö. 1Kor 13,12; 2Kor 5,6–8)! " +
            "Kiadatott 1992. október 11-én, a második Vatikáni Zsinat megnyitásának harmincadik évfordulóján, pápaságom tizennegyedik évében. ";
}
